// flow-typed signature: 1d489508193a2745e9f0ce04ce39bd39
// flow-typed version: <<STUB>>/simple-load-script_v^1.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-load-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-load-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-load-script/simpleLoadScript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-load-script/simpleLoadScript.js' {
  declare module.exports: $Exports<'simple-load-script/simpleLoadScript'>;
}
