// flow-typed signature: 53f56368a9c0a70884044619c4d1aa2d
// flow-typed version: <<STUB>>/webpack-spawn-plugin_v^0.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-spawn-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-spawn-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-spawn-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-spawn-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-spawn-plugin/dist/index'>;
}
declare module 'webpack-spawn-plugin/index' {
  declare module.exports: $Exports<'webpack-spawn-plugin'>;
}
declare module 'webpack-spawn-plugin/index.js' {
  declare module.exports: $Exports<'webpack-spawn-plugin'>;
}
