// flow-typed signature: d1c6d4bdb7d963f8c37750829c562cd2
// flow-typed version: <<STUB>>/webpack-blocks-server-source-map_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-blocks-server-source-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-blocks-server-source-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-blocks-server-source-map/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-blocks-server-source-map/dist/index.js' {
  declare module.exports: $Exports<'webpack-blocks-server-source-map/dist/index'>;
}
declare module 'webpack-blocks-server-source-map/index' {
  declare module.exports: $Exports<'webpack-blocks-server-source-map'>;
}
declare module 'webpack-blocks-server-source-map/index.js' {
  declare module.exports: $Exports<'webpack-blocks-server-source-map'>;
}
