// flow-typed signature: 7fcb66842527a9428062502a7bb013b2
// flow-typed version: <<STUB>>/webpack-assets-by-type-plugin_v^0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-assets-by-type-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-assets-by-type-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-assets-by-type-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-assets-by-type-plugin/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-assets-by-type-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-assets-by-type-plugin/dist/index'>;
}
declare module 'webpack-assets-by-type-plugin/dist/utils.js' {
  declare module.exports: $Exports<'webpack-assets-by-type-plugin/dist/utils'>;
}
declare module 'webpack-assets-by-type-plugin/index' {
  declare module.exports: $Exports<'webpack-assets-by-type-plugin'>;
}
declare module 'webpack-assets-by-type-plugin/index.js' {
  declare module.exports: $Exports<'webpack-assets-by-type-plugin'>;
}
