// flow-typed signature: dde3249bcfe33afe747a1da8eed1763f
// flow-typed version: <<STUB>>/webpack-blocks-happypack_v^0.1.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-blocks-happypack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-blocks-happypack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-blocks-happypack/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-blocks-happypack/dist/types' {
  declare module.exports: any;
}

declare module 'webpack-blocks-happypack/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-blocks-happypack/dist/index.js' {
  declare module.exports: $Exports<'webpack-blocks-happypack/dist/index'>;
}
declare module 'webpack-blocks-happypack/dist/types.js' {
  declare module.exports: $Exports<'webpack-blocks-happypack/dist/types'>;
}
declare module 'webpack-blocks-happypack/dist/utils.js' {
  declare module.exports: $Exports<'webpack-blocks-happypack/dist/utils'>;
}
declare module 'webpack-blocks-happypack/index' {
  declare module.exports: $Exports<'webpack-blocks-happypack'>;
}
declare module 'webpack-blocks-happypack/index.js' {
  declare module.exports: $Exports<'webpack-blocks-happypack'>;
}
