// flow-typed signature: f188b08f3b764dffc99979c31ff1b763
// flow-typed version: <<STUB>>/webpack-child-config-plugin_v^0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-child-config-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-child-config-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-child-config-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-child-config-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-child-config-plugin/dist/index'>;
}
declare module 'webpack-child-config-plugin/index' {
  declare module.exports: $Exports<'webpack-child-config-plugin'>;
}
declare module 'webpack-child-config-plugin/index.js' {
  declare module.exports: $Exports<'webpack-child-config-plugin'>;
}
